version: v1.0.0.{build}

platform: x64

clone_folder: c:\gopath\src\github.com\ennoo\rivet

environment:
  GOPATH: c:\gopath
  GO111MODULE: on
  GOFLAGS: -mod=readonly
  PKGSWITHOUTEXAMPLES: $(shell go list ./... | grep -v 'examples/')

install:
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env

build_script:
  - go vet $(PKGSWITHOUTEXAMPLES)
  - go test -v -race -cover $(PKGSWITHOUTEXAMPLES)
#  - go test -v -run - -bench . -benchmem ./...