version: 2
jobs:
  build:
    working_directory: /go/src/github.com/ennoo/rivet
    parallelism: 1
    docker:
      - image: circleci/golang
    steps:
      - checkout
      - run: go get -t -v -d ./...
      - run: make start check test end